name: Experienced Bills
version: 1.0
main: com.rrayy.EB.EB
api-version: '1.21'
author: rrayy
description: Experienced Bills is plugin for ATM of Minecraft XP
commands:
  atm:
      description: Get Bill of XP
      usage: /atm <Amount>